#!/usr/bin/env perl

use strict;
use warnings;

use Data::Dumper;

use Config::YAML;
use JSON;
use LWP::UserAgent::Determined;
use URI::Escape;

my $configFile = $ARGV[0] || "openweathermap_exporter.yml";
my $port = $ARGV[1] || "9091";

my $config = Config::YAML->new( config => $configFile);

my $ua = LWP::UserAgent::Determined->new;
$ua->timing("1,2,5");

my $output = "# TYPE weather_info gauge
# HELP weather_info Information about the location; the value equals the id of the location
# TYPE weather_return_code gauge
# HELP weather_return_code Internal API return code, presumably HTTP codes
# TYPE weather_temperature_kelvin gauge
# HELP weather_temperature_kelvin Temperature in Kelvin; for large areas, min/max might differ
# TYPE weather_measurement_epoch gauge
# HELP weather_measurement_epoch Unix timestamp of last measurement
# TYPE weather_wind_meters_per_second gauge
# HELP weather_wind_meters_per_second Speed in m/s
# TYPE weather_wind_direction gauge
# HELP weather_wind_direction Direction in meteorological degress
# TYPE weather_id gauge
# HELP weather_id Weather condition id
# TYPE weather_location_coordinates gauge
# HELP weather_location_coordinates Geolocation; latitude and longitude
# TYPE weather_humidity_percent gauge
# HELP weather_humidity_percent Relative humidity in percent
# TYPE weather_clouds_percent gauge
# HELP weather_clouds_percent Cloud cover in percent
# TYPE weather_sun_epoch gauge
# HELP weather_sun_epoch
# TYPE weather_pressure_hectopascal gauge
# HELP weather_pressure_hectopascal\n";

my @urls;
my $api_key = $config->{api_key};
my $pushgateway = defined $config->{pushgateway} ? $config->{pushgateway} : 'localhost:9091';

if ($config->{cities}) {
        foreach my $city (@{$config->{cities}}) {
                push @urls, "http://api.openweathermap.org/data/2.5/weather?q=". uri_escape($city) ."&appid=$api_key";
        }
}

if ($config->{latlons}) {
        foreach my $latlon (@{$config->{latlons}}) {
                my $lat = $latlon->[0];
                my $lon = $latlon->[1];
                push @urls, "http://api.openweathermap.org/data/2.5/weather?lat=$lat&lon=$lon&appid=$api_key";
        }
}

if ($config->{zips}) {
        foreach my $zip (@{$config->{zips}}) {
                push @urls, "http://api.openweathermap.org/data/2.5/weather?zip=$zip,us&appid=$api_key";
        }
}

foreach my $url (@urls) {
        my $api_key=$config->{api_key};
        my $json = $ua->get($url);

        #TODO count up errors instead of dying once this becomes a daemon
        die "Could not get $url: $!" unless $json->is_success;
        my $decoded_json = decode_json( $json->content );

        $output .= "weather_info{location=\"$decoded_json->{name}\",country=\"$decoded_json->{sys}{country}\"} $decoded_json->{id}\n";

        $output .= "weather_return_code{name=\"$decoded_json->{name}\"} $decoded_json->{cod}\n";

        $output .= "weather_temperature_kelvin{name=\"$decoded_json->{name}\",type=\"current\"} $decoded_json->{main}{temp}\n";
        $output .= "weather_temperature_kelvin{name=\"$decoded_json->{name}\",type=\"max\"} $decoded_json->{main}{temp_max}\n";
        $output .= "weather_temperature_kelvin{name=\"$decoded_json->{name}\",type=\"min\"} $decoded_json->{main}{temp_min}\n";

        $output .= "weather_measurement_epoch{name=\"$decoded_json->{name}\"} $decoded_json->{dt}\n";

        $output .= "weather_wind_meters_per_second{name=\"$decoded_json->{name}\"} $decoded_json->{wind}{speed}\n";

        # This is not always returned
        $output .= "weather_wind_direction{name=\"$decoded_json->{name}\"} $decoded_json->{wind}{deg}\n"
                if defined $decoded_json->{wind}{deg};

        # TODO I fear there might be multiple arrays in there, sometimes
        $output .= "weather_id{name=\"$decoded_json->{name}\"} $decoded_json->{weather}[0]{id}\n";

        $output .= "weather_location_coordinates{name=\"$decoded_json->{name}\",dimension=\"latitude\"} $decoded_json->{coord}{lat}\n";
        $output .= "weather_location_coordinates{name=\"$decoded_json->{name}\",dimension=\"longitude\"} $decoded_json->{coord}{lon}\n";

        $output .= "weather_humidity_percent{name=\"$decoded_json->{name}\"} $decoded_json->{main}{humidity}\n";

        $output .= "weather_clouds_percent{name=\"$decoded_json->{name}\"} $decoded_json->{clouds}{all}\n";

        $output .= "weather_sun_epoch{name=\"$decoded_json->{name}\",change=\"sunrise\"} $decoded_json->{sys}{sunrise}\n";
        $output .= "weather_sun_epoch{name=\"$decoded_json->{name}\",change=\"sunset\"} $decoded_json->{sys}{sunset}\n";

        $output .= "weather_pressure_hectopascal{name=\"$decoded_json->{name}\",level=\"current\"} $decoded_json->{main}{pressure}\n";
        $output .= "weather_pressure_hectopascal{name=\"$decoded_json->{name}\",level=\"ground\"} $decoded_json->{main}{grnd_level}\n" if defined $decoded_json->{main}{grnd_level};
        $output .= "weather_pressure_hectopascal{name=\"$decoded_json->{name}\",level=\"sea\"} $decoded_json->{main}{sea_level}\n" if defined $decoded_json->{main}{sea_level};

#       $output .= "weather_{name=\"$decoded_json->{name}\"} $decoded_json->{}{}\n";
}

my $response = $ua->post('http://'. $pushgateway .'/metrics/job/openweathermap_exporter',
                                Content_Type => 'form-data',
                                Content => $output);

$response->is_success ? exit 0 : print Dumper $response ; exit 1;

